#!/bin/sh /etc/rc.common

START=88
USE_PROCD=1

NAME=usteer-influxdb
PROG=/usr/bin/usteer-influxdb

. /lib/functions.sh


reload_service() {
	stop
	start
}

service_triggers() {
	procd_add_reload_trigger usteer-influxdb
}

start_service()
{
	DISABLED="$(uci -q get usteer-influxdb.settings.disabled)"
	DISABLED="${DISABLED:-0}"

	[ "$DISABLED" -eq 0 ] || return

	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}
